name: mouse_tracker
description: A Flutter plugin to track mouse position on macOS.
version: 0.0.1
homepage: https://github.com/tedEE/mouse_tracker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: MouseTrackerPlugin
